name: html5lib
version: 0.12.1
author: Dart Team <misc@dartlang.org>
description: (renamed to "package:html")
homepage: https://pub.dartlang.org/packages/html
dependencies:
  html: ^0.12.1
dev_dependencies:
  path: '>=0.9.0 <2.0.0'
  unittest: '>=0.10.0 <0.11.0'
